[program:wechat_bot]
command=/root/anaconda3/envs/pytorch_remote/bin/python /root/myProject/learning/06-项目/01-AI医生/wr.py
autostart=true
autorestart=true
startsecs=5
stderr_logfile=/root/myProject/learning/06-项目/01-AI医生/logs/wechat_bot.err.log
stdout_logfile=/root/myProject/learning/06-项目/01-AI医生/logs/wechat_bot.out.log
stderr_logfile_maxbytes=50MB
stdout_logfile_maxbytes=50MB
stderr_logfile_backups=5
stdout_logfile_backups=5
user=root
directory=/root/myProject/learning/06-项目/01-AI医生
environment=PYTHONUNBUFFERED=1

[program:reply_end]
command=/root/anaconda3/envs/pytorch_remote/bin/gunicorn -w 1 -b 0.0.0.0:5000 app:app
autostart=true
autorestart=true
startsecs=10
stderr_logfile=/root/myProject/learning/06-项目/01-AI医生/logs/reply_end.err.log
stdout_logfile=/root/myProject/learning/06-项目/01-AI医生/logs/reply_end.out.log
stderr_logfile_maxbytes=50MB
stdout_logfile_maxbytes=50MB
stderr_logfile_backups=5
stdout_logfile_backups=5
user=root
directory=/root/myProject/learning/06-项目/01-AI医生/docker_online/main_serve
environment=PYTHONUNBUFFERED=1

[program:recognition_end]
command=/root/anaconda3/envs/pytorch_remote/bin/gunicorn -w 1 -b 0.0.0.0:5001 app:app
autostart=true
autorestart=true
startsecs=10
stderr_logfile=/root/myProject/learning/06-项目/01-AI医生/logs/recognition_end.err.log
stdout_logfile=/root/myProject/learning/06-项目/01-AI医生/logs/recognition_end.out.log
stderr_logfile_maxbytes=50MB
stdout_logfile_maxbytes=50MB
stderr_logfile_backups=5
stdout_logfile_backups=5
user=root
directory=/root/myProject/learning/06-项目/01-AI医生/docker_online/bert_serve
environment=PYTHONUNBUFFERED=1
